version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    command: >
      sh -c "npm run deploy:prisma"
    # run with sql script:
    #   sh -c "npm run deploy:sql"
    healthcheck:
      test: curl -f http://localhost:3001/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # volumes:
    #   - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Este volume é usado para executar scripts SQL na inicialização caso não queira usar prisma
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
