import { IngredientName, JuiceName } from '../../src/types/basicTypes'

export const juiceIngredientMapping: Record<JuiceName, IngredientName[]> = {
  'Matcha SharkLatte': ['Matcha', 'Leite de amêndoas'],
  'Shark Cold Brew': ['Café', 'Leite de coco'],
  'Chá Gelado de Pêssego': ['Pêssego', 'Hortelã'],
  'Limonada com Hortelã': ['Limão', 'Hortelã'],
  'Suco de Laranja': ['Laranja'],
  'Suco de Maçã': ['Maçã'],
  'Suco Verde': ['Couve', 'Limão'],
  'Suco de Abacaxi': ['Abacaxi', 'Hortelã'],
  'Suco de Uva': ['Uva'],
  'Suco de Morango': ['Morango', 'Limão'],
  'Suco de Melancia': ['Melancia'],
  'Suco de Manga': ['Manga'],
  'Suco de Acerola': ['Acerola'],
  'Suco de Maracujá': ['Maracujá'],
  'Suco de Limão': ['Limão'],
  'Suco de Goiaba': ['Goiaba'],
  'Suco Detox': ['Couve', 'Limão', 'Gengibre'],
  'Suco Energético': ['Açaí', 'Banana', 'Guaraná'],
  'Suco Anti-inflamatório': ['Abacaxi', 'Cúrcuma', 'Pimenta Cayena'],
  'Suco de Beterraba': ['Beterraba', 'Laranja', 'Gengibre'],
  'Suco Verde Detox': ['Pepino', 'Espinafre', 'Limão'],
  'Suco de Cenoura': ['Cenoura', 'Laranja', 'Gengibre'],
  'Soda Italiana de Morango': ['Morango'],
  'Soda Italiana de Limão': ['Limão'],
  'Soda Italiana de Maçã Verde': ['Maçã Verde'],
  'Soda Italiana de Laranja': ['Laranja'],
  'Soda Italiana de Uva': ['Uva'],
  'Soda Italiana de Cereja': ['Cereja'],
  'Thai Iced Tea': ['Chá tailandês', 'Leite condensado'],
  'Thai Iced Coffee': ['Café', 'Leite de coco'],
  'Thai Lemonade': ['Limão', 'Capim-limão'],
  'Thai Coconut Drink': ['Coco'],
  'Thai Milk Tea': ['Chá tailandês', 'Leite', 'Especiarias'],
  'Thai Fruit Punch': ['Frutas exóticas'],
  'Coca-cola': [],
  'Red bull': [],
  'Água de Coco': ['Coco'],
  'Gin Tônica': ['Gin', 'Tônica'],
  Sprite: ['Limão'],
  Pepsi: [],
  Guaraná: ['Guaraná']
}
